### ISSUE TITLE
using gui times out or goes into indefinite loop

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/whisper#14]
http://showterm.io/7462a54a2cef378d40ffb

**Comment by draganglumac** [comment]
:( seems like it doesn't strip the new line character from the command string that's why name lookup fails

http://showterm.io/34ab5463f01a3a86f5969

Yet to investigate looking up twice getting stuck.

**Comment by AlexsJones** [comment]
My bug then thanks for looking
