### ISSUE TITLE
Establishing session fails during initiation of secure connection.

### ISSUE THREAD

**Issue by draganglumac** [AlexsJones/whisper#38]
http://showterm.io/69c2315e256520202e97f
Another problem that happens on establishing a session from Mac to Linux - with a backtrace.

**Comment by draganglumac** [comment]
This one with a backtrace - same problem

http://showterm.io/69c2315e256520202e97f

**Comment by draganglumac** [comment]
Another failure at the same place I think, but this time for a different reason.

http://showterm.io/fff0c3bbb433b8db92613

**Comment by AlexsJones** [comment]
The first one looks like the thread running getaddrinfo has run out of stack space possibly. 
We'll have to check the buffer size.
https://sourceware.org/bugzilla/show_bug.cgi?id=10652
http://stackoverflow.com/questions/26063276/getaddrinfo-and-gethostbyname-crashing-when-called-from-child-thread

**Comment by draganglumac** [comment]
Will look at this post GUI hookup.
