### ISSUE TITLE
Session getting stuck before initiator starts on Mac

### ISSUE THREAD

**Issue by draganglumac** [AlexsJones/whisper#39]
Compiled with clang, run through LLDB, thread dump for all threads.

http://showterm.io/04ac38b6e0bc8aebb0feb

**Comment by AlexsJones** [comment]
I guess this as same as the other issue, but ill keep that one open. Try new fix

**Comment by draganglumac** [comment]
Will look at this post GUI hookup.

**Comment by AlexsJones** [comment]
Identified this as the remote_peer->host_address is becoming invalid half way through auth_comms and means the `tcp_send_with_receipt` fails

**Comment by AlexsJones** [comment]
This should be fixed

**Comment by AlexsJones** [comment]
```
 void *finish_object;
printf("Checking object type 2.\n");
if(handshake_did_receive_receiver_request(replytwo,replysizetwo,&finish_object)){
printf("Unpacked auth receiver request\n");
AuthReceiver *ar = (AuthReceiver *)finish_object;  //This was wrong and refering to object from previous
```
