### ISSUE TITLE
Increase types accessing JNXLIBC api

### ISSUE THREAD

**Issue by AlexsJones** [AlexsJones/whisper#4]
/home/tibbar/projects/whisper/src/net/discovery.c: In function ‘polling_update_strategy’:
/home/tibbar/projects/whisper/src/net/discovery.c:115:21: warning: assignment makes pointer from integer without a cast [enabled by default]
  svc->update_thread = jnx_thread_create_disposable(polling_update_loop, (void *) svc);
                     ^
/home/tibbar/projects/whisper/src/net/discovery.c: In function ‘broadcast_update_strategy’:
/home/tibbar/projects/whisper/src/net/discovery.c:136:21: warning: assignment makes pointer from integer without a cast [enabled by default]
  svc->update_thread = jnx_thread_create_disposable(broadcast_update_loop, (void *) svc);
                     ^
/home/tibbar/projects/whisper/src/net/discovery.c: In function ‘stop_listening’:
/home/tibbar/projects/whisper/src/net/discovery.c:185:2: warning: passing argument 1 of ‘ioctl’ makes integer from pointer without a cast [enabled by default]
  return ioctl(svc->sock_receive, FIONBIO, (char *) &dont_block);
  ^
In file included from /home/tibbar/projects/whisper/src/net/discovery.c:19:0:
/usr/include/i386-linux-gnu/sys/ioctl.h:41:12: note: expected ‘int’ but argument is of type ‘struct jnx_socket *’
 extern int ioctl (int __fd, unsigned long int __request, ...) __THROW;
            ^
/home/tibbar/projects/whisper/src/net/discovery.c: In function ‘set_up_sockets_for_multicast’:
/home/tibbar/projects/whisper/src/net/discovery.c:199:2: warning: passing argument 3 of ‘jnx_socket_udp_enable_multicast_send’ makes integer from pointer without a cast [enabled by default]
  jnx_socket_udp_enable_multicast_send(svc->sock_send, "todo", "todo");
  ^
In file included from /home/tibbar/projects/whisper/src/net/discovery.c:20:0:
/usr/include/jnxc_headers/jnxsocket.h:93:12: note: expected ‘jnx_int32’ but argument is of type ‘char *’
   jnx_size jnx_socket_udp_enable_multicast_send(jnx_socket *s, jnx_char *interface, jnx_int32 ignore_local);
            ^
/home/tibbar/projects/whisper/src/net/discovery.c: In function ‘discovery_service_stop’:
/home/tibbar/projects/whisper/src/net/discovery.c:247:3: warning: passing argument 1 of ‘cancel_thread’ from incompatible pointer type [enabled by default]
   cancel_thread(svc->update_thread);
   ^
/home/tibbar/projects/whisper/src/net/discovery.c:176:13: note: expected ‘struct jnx_thread **’ but argument is of type ‘struct jnx_thread *’
 static void cancel_thread(jnx_thread **thr) {

**Comment by draganglumac** [comment]
You want me to use all jinxified types here eh?
